name: cast_data
description: >
  Safely cast dynamic data, especially JSON data as intended type by performing data validation first
  and take alternative action in case data cannot be casted.
version: 0.0.0
homepage: https://github.com/P-YNPM/cast-data

environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
