name: parse_data
description: >
  Safely parse dynamic data, especially JSON data as intended type
  and take alternative action in case data cannot be parsed.
  Avoiding implicit down-casting
version: 0.0.0
homepage: https://github.com/P-YNPM/parse-data

environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
